### ISSUE TITLE
Error while parsing string

### ISSUE THREAD

**Issue by johnblommers** [ws-kj/Orphic#1]
```bash
orphic how much space is free on the boot volume
EOF while parsing a string at line 1 column 43
{"command": "df -h / | awk 'NR==2{print $4}'"}
```

The actual command `df -h / | awk 'NR==2{print $4}'` itself works fine when you copy and paste it on the commandline. This is for orphic 0.1.0. I'm running on PopOS 22.04 an Ubuntu derivative. My rustc is at 1.68.0. I installed via `cargo install orphic`

Update. Another example of this:

```bash
orphic show me the name and size of all files larger than one gigabyte in my home directory
EOF while parsing a string at line 1 column 81
EOF while parsing a string at line 1 column 81
{"command": "find ~/ -type f -size +1G -printf '{\"name\":\"%f\",\"size\":\"%s\"}\\n'" }
```

**Comment by ws-kj** [comment]
I think there is an issue with serialization when the command contains quotes. I will try to fix this today.

**Comment by ws-kj** [comment]
Fixed. Was ending the command string at first } instead of last.

**Comment by johnblommers** [comment]
Confirmed fixed.

I also like the addition of a `Execute? [Y/n]` prompt`  as that is SO prudent for this tool. Nicely done!

**Comment by ws-kj** [comment]
Personally I think it's more fun to just let it execute whatever it comes up with. It feels like magic to me. However public consensus seems to be that it's a little too scary, hence the new prompt.
