### ISSUE TITLE
cd command does not work.

### ISSUE THREAD

**Issue by ScripterSugar** [ws-kj/Orphic#12]
Executing this command
`orphic locate into test directory`
Returns command
`cd test`
and when I execute this through orphic it won't take me to the directory.

**Comment by ws-kj** [comment]
Commands are executed in a new process separate from the process of your shell environment, so cd will not take effect in your shell unfortunately. There are no workarounds to this (to the best of my knowledge).

**Comment by ScripterSugar** [comment]
Well, that was my guess as well. Thank you for the answer anyway 👍 

Maybe it'd be nice to document this in readme.
