### ISSUE TITLE
Allow users to view the command and approve or reject it before it runs

### ISSUE THREAD

**Issue by JoeyEamigh** [ws-kj/Orphic#3]
This would allow for greater peace of mind before running a command, and allow users to not run a command if it seems dangerous.

I may open a PR to do this myself if I have time in the future.

**Comment by ws-kj** [comment]
It probably would be good to have this as the default setting. I'll try to get it done today.

**Comment by ws-kj** [comment]
Added this as the default behavior. Can be bypassed with -u.
