### ISSUE TITLE
Error when passing API key

### ISSUE THREAD

**Issue by U2C9727A4** [ws-kj/Orphic#4]
Ive tried to pass orphic the API key with `$OPENAI_API_KEY` envoirment variable but it thinks i didnt provide any keys (its a variable in the bash shell which is the shell i use in my terminal if it isnt  the right way to do it then show me please)

**Comment by ws-kj** [comment]
The API key is handled by the `async-openai` crate, so there shouldn't be any issues specific to this project. As long as the env var is set in the current shell context that you run the command from it should work. Maybe try adding it to your shell config file if you haven't done that and are just manually exporting it every time.

**Comment by Taiwing** [comment]
Just add `export OPEN_API_KEY=<your key>` to your ~/.profile or to your ~/.bashrc, ~/.zshrc or ~/.whateverrc. Then run `source ~/.<your profile or config>` in your shell to update your environment.
