### ISSUE TITLE
stream output of long-running command execution to stdout?

### ISSUE THREAD

**Issue by ScripterSugar** [ws-kj/Orphic#9]
Hi. I'm trying orphic on mac machine with zsh.

When I execute long-running command like "top", the program simply stucks after confirmation, and I have to abort manually and execute command on my own. 

It'd be nice if we can use these types of commands seamlessly :)

**Comment by ws-kj** [comment]
I'll add this.

**Comment by ws-kj** [comment]
Added. Not yet on crates.io but you can build from repo.
